version: 2

models:

  - name: stg__brands
    description: "This model contains a list of bike brands"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg__products')
              field: brand_id
        
  - name: stg__categories
    description: "This model contains list of bike categories."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg__products')
              field: category_id

  
  - name: stg__customers
    description: "This model contains information on local bike customers with sensitive information"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg__orders')
              field: customer_id


  - name: stg__order_items
    description: "This model contains detailed information on order items, product_id, price, discount and other amounts"
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order line generated by concatenating order_id and item_id"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key, unqiue identifier for each order"
        tests:
          - relationships:
              to: ref('stg__orders')
              field: order_id

  - name: stg__products
    description: "This model contains product list, with product name and links to categories and brands, includes list price and model year"
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product"
        tests:
          - unique
          - not_null

  - name: stg__staffs
    description: "This model contains list of local bike staff memebers by store"
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member"
        tests:
          - unique
          - not_null


  - name: stg__stocks
    description: "This model contains information on current stock status in each store by product id"
    columns:
      - name: store_id
      - name: product_id
      - name: stock_quantity

  - name: stg__stores
    description: "This model contains information on local bike stores and address details"
    columns:
      - name: store_id
        description: "Primary key, unique identifier of the store"
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg__orders')
              field: store_id





